export const collegeOptions = [
	'IIM Calcutta, Kolkata',
	'International Mgmt. Institute (IMI), Kolkata',
	'Indian Institute of Social Welfare & Business Mgmt. (IISWBM), Kolkata',
	'Eastern Institute of Integrated Learning in Mgmt. (EIILM), Kolkata',
	'Institute of Leadership, Exc. & Development (iLEAD), Kolkata',
	'Globsyn Business School, Kolkata',
	'The Bhawanipur Edn. Society College, Kolkata',
	'JD Birla Institute, Kolkata',
	"St. Xavier's College, Kolkata",
	'Jadavpur University, Kolkata',
	'Institute of Engineering & Management, Kolkata',
	'Heritage Institute of Technology, Kolkata',
	'NSHM "Bhawanipur" Global Campus, Kolkata',
	'B. P. Poddar Institute of Management and Technology, Kolkata',
	'Future Institute of Engineering & Management, Kolkata',
	'Calcutta Institute of Engg. & Mgmt., Kolkata',
	'Dr. M. G. R. Educational & Research Institute, Kolkata',
	'Amity University, Kolkata',
	'Sister Nivedita University, Kolkata',
	'ICFAI University, Kolkata',
	'University of Engineering & Management (UEM), Kolkata',
	'Techno India University, Kolkata',
	'Pailan College of Mgmt. & Tech., Kolkata',
	'NSHM Knowledge Campus, Kolkata (Durgapur & Kolkata branches)',
	'Narula Institute of Technology, Kolkata',
	'Netaji Subhash Engineering College, Kolkata',
	'Government College of Engg. & Leather Tech., Kolkata',
	'RCC Institute of Information Technology, Kolkata',
	'Dr. Sudhir Chandra Sur Degree Engg. College, Kolkata',
	'Camellia Institute of Technology, Kolkata',
	"St. Thomas' College of Engg. & Tech., Kolkata",
	'B. P. Poddar Institute of Computer Science & Technology, Kolkata',
	'Swami Vivekananda Institute of Sci. & Tech., Kolkata',
	'Heritage Academy, Kolkata',
	'Shri Shikshayatan College, Kolkata',
	'Asutosh College, Kolkata',
	'Techno India College of Technology (TINT), Kolkata',
	'Guru Nanak Institute of Technology, Kolkata',
	'Gargi Memorial Institute of Technology, Kolkata',
	'Techno Global Balurghat, Balurghat',
	'Bankura Unnayani Institute of Engg., Bankura',
	'Budge Budge Institute of Technology, Kolkata',
	'University Institute of Technology, Burdwan University (UITBU)',
	'Dr. B. C. Roy Engg. College, Durgapur',
	'Academy of Technology, Adisaptagram (Hooghly)',
	'Hooghly Engineering & Technology College, Hooghly',
	'Academy of Technology, Hooghly',
	'Indian Institute of Engineering Science and Technology, Shibpur',
	'Seacom Engineering College, Sankrail, Howrah',
	'Jalpaiguri Government Engineering College, Jalpaiguri',
	'Kalyani Government Engineering College, Kalyani',
	'JIS College of Engineering, Kalyani',
	'Birbhum Institute of Engg. & Technology, Suri',
	'Kanksa Academy of Technology & Management, Bardhaman',
	'Greater Kolkata College of Engg. & Mgmt., Baruipur, Kolkata',
	'Bengal Institute of Technology & Management, Santiniketan',
	'Durgapur Institute of Advanced Tech. & Mgmt., Durgapur',
	'Global Institute of Mgmt. & Technology, Krishnanagar',
	'Surendra Institute of Engg. & Mgmt., Siliguri',
	'Haldia Institute of Technology, Haldia',
	'MCKV Institute of Engineering, Howrah',
	'Indian Institute of Technology, Kharagpur',
	'Siliguri Institute of Technology, Siliguri',
	'Adamas Institute of Technology (Adamas Univ.), Barasat',
	'Asansol Engineering College, Asansol',
	'Bengal College of Engg. & Technology, Durgapur (BCET)',
	'National Institute of Technology, Durgapur',
	'Other'
] as const;

export const departmentOptions = [
	'B.Tech (Bachelor of Technology)',
	'B.E. (Bachelor of Engineering)',
	'BCA (Bachelor of Computer Applications)',
	'B.Sc IT (Bachelor of Science in Information Technology)',
	'B.Sc Computer Science (Bachelor of Science in Computer Science)',
	'BBA (Bachelor of Business Administration)',
	'BMS (Bachelor of Management Studies)',
	'B.Com (Bachelor of Commerce)',
	'BFM (Bachelor of Financial Markets)',
	'BAF (Bachelor of Accounting & Finance)',
	'BBI (Bachelor of Banking & Insurance)',
	'B.Sc (Bachelor of Science)',
	'B.Sc Biotechnology (Bachelor of Science in Biotechnology)',
	'B.Sc Microbiology (Bachelor of Science in Microbiology)',
	'B.Sc Agriculture (Bachelor of Science in Agriculture)',
	'B.Sc Nursing (Bachelor of Science in Nursing)',
	'BA (Bachelor of Arts)',
	'BA Journalism (Bachelor of Arts in Journalism)',
	'BA Mass Communication (Bachelor of Arts in Mass Communication)',
	'LLB (Bachelor of Laws)',
	'BA LLB (Bachelor of Arts + Bachelor of Laws)',
	'BBA LLB (Bachelor of Business Administration + Bachelor of Laws)',
	'B.Com LLB (Bachelor of Commerce + Bachelor of Laws)',
	'Others'
] as const;

export const interestOptions = [
	'Career & Growth',
	'Software Development',
	'Data & AI',
	'DevOps & Cloud',
	'Business & Management',
	'Marketing',
	'Finance',
	'Creative',
	'Academics',
	'Sports & Gaming',
	'Lifestyle',
	'Filmmaking',
	'Chess',
	'Streaming',
	'Entrepreneurship',
	'Product Management',
	'Human Resources',
	'Public Speaking',
	'Web Development',
	'App Development',
	'Game Development',
	'Cybersecurity',
	'Deep Learning',
	'Prompt Engineering',
	'Copywriting',
	'Stock Market',
	'Accounting',
	'GATE',
	'CAT',
	'JEE',
	'NEET',
	'CET',
	'CA',
	'GOV Job',
	'UI/UX Design',
	'Graphic Design',
	'Animation',
	'Politics',
	'College Placement'
] as const;
