import { defaultSchema, type Options as SanitizeSchema } from 'rehype-sanitize';

const staticSvgTags = [
	'svg',
	'g',
	'path',
	'circle',
	'ellipse',
	'line',
	'polyline',
	'polygon',
	'rect',
	'text',
	'tspan',
	'defs',
	'linearGradient',
	'radialGradient',
	'stop',
	'clipPath',
	'mask',
	'title',
	'desc'
];

const staticSvgAttributes = [
	'ariaHidden',
	'ariaLabel',
	'clipPath',
	'clipRule',
	'cx',
	'cy',
	'd',
	'dx',
	'dy',
	'fill',
	'fillOpacity',
	'fillRule',
	'fontFamily',
	'fontSize',
	'fontWeight',
	'fx',
	'fy',
	'gradientTransform',
	'gradientUnits',
	'height',
	'lengthAdjust',
	'mask',
	'offset',
	'opacity',
	'orient',
	'pathLength',
	'points',
	'preserveAspectRatio',
	'r',
	'rx',
	'ry',
	'spreadMethod',
	'stopColor',
	'stopOpacity',
	'stroke',
	'strokeDasharray',
	'strokeDashoffset',
	'strokeLinecap',
	'strokeLinejoin',
	'strokeMiterlimit',
	'strokeOpacity',
	'strokeWidth',
	'textAnchor',
	'textLength',
	'transform',
	'vectorEffect',
	'viewBox',
	'width',
	'x',
	'x1',
	'x2',
	'y',
	'y1',
	'y2'
];

export const lessonMarkdownSanitizeSchema: SanitizeSchema = {
	...defaultSchema,
	tagNames: [
		...(defaultSchema.tagNames ?? []),
		'audio',
		'button',
		'embed',
		'iframe',
		'object',
		'option',
		'select',
		'textarea',
		'video',
		...staticSvgTags
	],
	attributes: {
		...defaultSchema.attributes,
		'*': [...(defaultSchema.attributes?.['*'] ?? []), 'ariaLabel', 'ariaDescribedBy', 'role'],
		audio: ['autoPlay', 'controls', 'loop', 'muted', 'preload', 'src', 'title'],
		button: [['type', 'button'], 'disabled', 'value'],
		div: [...(defaultSchema.attributes?.div ?? []), ['className', 'math', 'math-display']],
		embed: ['height', 'src', ['type', 'application/pdf'], 'width'],
		iframe: ['allow', 'allowFullScreen', 'height', 'loading', 'referrerPolicy', 'src', 'title', 'width'],
		img: [...(defaultSchema.attributes?.img ?? []), 'alt', 'height', 'loading', 'title', 'width'],
		input: [
			['type', 'text', 'range', 'checkbox'],
			'checked',
			'disabled',
			'max',
			'maxLength',
			'min',
			'placeholder',
			'readOnly',
			'step',
			'value'
		],
		object: ['data', 'height', ['type', 'application/pdf'], 'width'],
		option: ['disabled', 'label', 'selected', 'value'],
		select: ['disabled', 'multiple', 'size'],
		source: [...(defaultSchema.attributes?.source ?? []), 'media', 'src', 'type'],
		svg: staticSvgAttributes,
		g: staticSvgAttributes,
		path: staticSvgAttributes,
		circle: staticSvgAttributes,
		ellipse: staticSvgAttributes,
		line: staticSvgAttributes,
		polyline: staticSvgAttributes,
		polygon: staticSvgAttributes,
		rect: staticSvgAttributes,
		text: staticSvgAttributes,
		tspan: staticSvgAttributes,
		defs: staticSvgAttributes,
		linearGradient: staticSvgAttributes,
		radialGradient: staticSvgAttributes,
		stop: staticSvgAttributes,
		clipPath: staticSvgAttributes,
		mask: staticSvgAttributes,
		span: [...(defaultSchema.attributes?.span ?? []), ['className', 'math', 'math-inline']],
		textarea: ['cols', 'disabled', 'maxLength', 'placeholder', 'readOnly', 'rows'],
		video: [
			'autoPlay',
			'controls',
			'height',
			'loop',
			'muted',
			'playsInline',
			'poster',
			'preload',
			'src',
			'title',
			'width'
		]
	},
	protocols: {
		...defaultSchema.protocols,
		data: ['http', 'https'],
		href: ['http', 'https', 'mailto'],
		poster: ['http', 'https'],
		src: ['http', 'https'],
		srcSet: ['http', 'https']
	},
	strip: [...(defaultSchema.strip ?? []), 'script', 'style']
};
